---
driver:
  name: terraform
  root_module_directory: test/fixtures
  # ################
  # Uncomment the following two lines if you are deploying /test/fixture/single-account/main.tf
  # using custom tfvars file
  #  variable_files:
  #    - test/fixtures/single-account/test.tfvars
  # ################
  parallelism: 4

provisioner:
  name: terraform

platforms:
  - name: "aws"

suites:
  - name: single-account
    driver:
      root_module_directory: test/fixtures/single-account
  - name: organizatioal
    driver:
      root_module_directory: test/fixtures/organizational
#    verifier:
#      name: "awspec"
#      patterns:
#        - "test/integration/kt_suite/single-account.rb"
