---
driver:
  name: terraform
  root_module_directory: test/fixtures/single-account
  # ################
  # Uncomment the following two lines if you are deploying /test/fixture/single-account/main.tf
  # using custom tfvars file
  #  variable_files:
  #    - test/fixtures/single-account/test.tfvars
  # ################
  parallelism: 4

provisioner:
  name: terraform

verifier:
  name: "awspec"

platforms:
  - name: "aws"

suites:
  - name: kt_suite
    verifier:
      name: "awspec"
      patterns:
        - "test/integration/kt_suite/single-account.rb"
