name: CI - Integration Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.tf'
      - '.github/workflows/**'
  push:
    branches:
      - master
    paths:
      - '**.tf'
      - '.github/workflows/**'
concurrency: terraform

jobs:
  integration_test:
    name: Test-Kitchen-ECS/EKS
    runs-on: ubuntu-latest
    env:
      TF_VAR_sysdig_secure_endpoint: https://secure.sysdig.com
      TF_VAR_sysdig_secure_api_token: ${{secrets.KUBELAB_SECURE_API_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Run single-account test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_CLOUDNATIVE_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: bundle exec kitchen test "single-account-aws"

      - name: Destroy single-account resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_CLOUDNATIVE_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        if: ${{ failure() }}
        run: bundle exec kitchen destroy "single-account-aws"

      - name: Run organizational test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_MANAGED_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_MANAGED_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_sysdig_secure_for_cloud_member_account_id: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCOUNT_ID }}
        run: bundle exec kitchen test "organizational-aws"

      - name: Destroy organizational resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_MANAGED_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_MANAGED_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_sysdig_secure_for_cloud_member_account_id: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCOUNT_ID }}
        if: ${{ failure() }}
        run: bundle exec kitchen destroy "organizational-aws"

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Run single-account-k8s test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_CLOUDNATIVE_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: bundle exec kitchen test "single-account-aws-k8s"

      - name: Destroy single-account-k8s resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_CLOUDNATIVE_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        if: ${{ failure() }}
        run: bundle exec kitchen destroy "single-account-k8s-aws"
