name: CI - Integration Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.tf'
      - '.github/workflows/**'
  push:
    branches:
      - master
    paths:
      - '**.tf'
      - '.github/workflows/**'
concurrency: terraform

jobs:
  integration_test:
    name: Test-Kitchen-ECS/EKS
    runs-on: ubuntu-latest
    env:
      TF_VAR_sysdig_secure_endpoint: https://secure.sysdig.com
      TF_VAR_sysdig_secure_api_token: ${{secrets.KUBELAB_SECURE_API_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Run single-account test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_CLOUDNATIVE_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: bundle exec kitchen test single-account

      - name: Destroy single-account resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_CLOUDNATIVE_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        if: ${{ failure() }}
        run: bundle exec kitchen destroy single-account

      - name: Run organizational test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_MANAGED_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_MANAGED_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_sysdig_secure_for_cloud_member_account_id: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCOUNT_ID }}
        run: bundle exec kitchen test "organizational-aws"

      - name: Destroy organizational resources
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_MANAGED_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_MANAGED_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_sysdig_secure_for_cloud_member_account_id: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCOUNT_ID }}
        if: ${{ failure() }}
        run: bundle exec kitchen destroy "organizational-aws"

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Organizational-k8s-reuse-cloudtrail
        env:
          TF_VAR_region: ${{ secrets.AWS_QA_MANAGED_RESOURCES_REGION }}
          TF_VAR_cloudtrail_s3_name : ${{ secrets.AWS_QA_MANAGED_CLOUDTRAIL_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_MANAGED_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_MANAGED_SECRET_ACCESS_KEY }}
          TF_VAR_org_accessKeyId: ${{ secrets.AWS_QA_MANAGED_ACCESS_KEY_ID }}
          TF_VAR_org_secretAccessKey: ${{ secrets.AWS_QA_MANAGED_SECRET_ACCESS_KEY }}
          TF_VAR_cloudnative_accessKeyId: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCESS_KEY_ID }}
          TF_VAR_cloudnative_secretAccessKey: ${{ secrets.AWS_QA_CLOUDNATIVE_SECRET_ACCESS_KEY }}
        run: bundle exec kitchen test "organizational-k8s-reuse-cloudtrail-aws"

      - name: Destroy Organizational-k8s-reuse-cloudtrail resources
        env:
          TF_VAR_region: ${{ secrets.AWS_QA_MANAGED_RESOURCES_REGION }}
          TF_VAR_cloudtrail_s3_name : ${{ secrets.AWS_QA_MANAGED_CLOUDTRAIL_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_QA_MANAGED_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_QA_MANAGED_SECRET_ACCESS_KEY }}
          TF_VAR_org_accessKeyId: ${{ secrets.AWS_QA_MANAGED_ACCESS_KEY_ID }}
          TF_VAR_org_secretAccessKey: ${{ secrets.AWS_QA_MANAGED_SECRET_ACCESS_KEY }}
          TF_VAR_cloudnative_accessKeyId: ${{ secrets.AWS_QA_CLOUDNATIVE_ACCESS_KEY_ID }}
          TF_VAR_cloudnative_secretAccessKey: ${{ secrets.AWS_QA_CLOUDNATIVE_SECRET_ACCESS_KEY }}
        if: ${{ failure() }}
        run: bundle exec kitchen destroy "organizational-k8s-reuse-cloudtrail-aws"
